name: build

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  dists:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8', '3.x' ]
    
    name: dists (${{ matrix.python-version }})
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --preview
          ln -s $HOME/.local/bin/poetry ./poetry
          ./poetry config virtualenvs.create false
          ./poetry install --no-root
      
      - name: Build distributions
        run: |
          ./poetry build
      
      - name: Install package
        run: |
          python -m pip install -e .
